framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus:
            event.bus:
                default_middleware: allow_no_handlers
            message.bus:
                default_middleware: allow_no_handlers

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: 'redis://%env(resolve:REDIS_HOST)%/0'
                options:
                    stream: messages
                    group: symfony
                    consumer: default
                    auto_setup: true
                    delete_after_ack: true
                    stream_max_entries: 10000
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Shared\Domain\Message\ChannelVerificationMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
